"""Base database store."""
from abc import ABC, abstractmethod
from typing import Optional

class BaseDatabaseStore(ABC):
    @abstractmethod
    def connect(self, connection_string: str, **kwargs) -> None: ...
    @abstractmethod
    def insert(self, data: dict, table: str) -> None: ...
    @abstractmethod
    def query(self, query: str, params: Optional[dict] = None) -> list[dict]: ...
    @abstractmethod
    def schema(self, table: Optional[str] = None) -> dict: ...
    @abstractmethod
    def tables(self) -> list[str]: ...
